-- Idempotent Materialize objects for ingesting from SQL Server CDC.

SET cluster = "$(MZ_CLUSTER_NAME)";

CREATE SECRET IF NOT EXISTS "$(MZ_SECRET_NAME)"
AS '$(SQLSERVER_PASSWORD)';

CREATE CONNECTION IF NOT EXISTS "$(MZ_CONNECTION_NAME)"
TO SQL SERVER (
    HOST '$(SQLSERVER_HOST)',
    PORT $(SQLSERVER_PORT),
    DATABASE '$(SQLSERVER_DATABASE)',
    USER '$(SQLSERVER_USER)',
    PASSWORD SECRET "$(MZ_SECRET_NAME)"
);

CREATE SOURCE IF NOT EXISTS "$(MZ_SOURCE_NAME)"
FROM SQL SERVER CONNECTION "$(MZ_CONNECTION_NAME)"
FOR TABLES ($(SQLSERVER_SCHEMA).$(SQLSERVER_TABLE));

-- Show what was created/resolved.
SHOW CONNECTIONS;
SHOW SOURCES;
